### ISSUE TITLE
Remote exec of volume mount doesn't work.

### ISSUE THREAD

**Issue by joegasewicz** [digitalocean/terraform-provider-digitalocean#1060]
I want to mount my volume for my droplet via a call to a remote exec:

```
  provisioner "remote-exec" {
    inline = [
      "mkdir -p /mnt/notto_media_1",
      "mount -o discard,defaults /dev/disk/by-id/scsi-0DO_Volume_notto-media-1 /mnt/notto_media_1",
      "echo /dev/disk/by-id/scsi-0DO_Volume_notto-media-1 /mnt/notto_media_1 ext4 defaults,nofail,discard 0 0 | sudo tee -a /etc/fstab"
    ]
  }
```

This doesn't work, if i ssh into the droplet where the remote exec is called in, I get no mounted volume:
```
findmnt /mnt/notto_media_1 # produces nothing
```

I therefore have to stop my docker compose stack, mount it manually in the droplet, then restart the docker compose stack, this works. 

Is there a way to run this mounting from the terraform config script with a remote exec call? I use docker's bind volume to bind to the volume disc via docker compose volume bind:

```
services:
  main_app:
    image: "bandnoticeboard/nottoboard:main_app-v0.0.4"
    env_file:
      - .env
    volumes:
      - static:/static
      - type: bind
        source: /mnt/notto_media_1
        target: /media
...etc
```

The main terraform config:

```
resource "digitalocean_droplet" "nottoboard-web" {
  image  = "docker-20-04"
  name   = "nottoboard-web"
  region = "lon1"
  size   = "s-1vcpu-1gb"
  ssh_keys = [
    data.digitalocean_ssh_key.nottoboard.id
  ]

  connection {
    host = self.ipv4_address
    user = "root"
    type = "ssh"
    private_key = file(var.pvt_key)
    timeout = "2m"
  }
.... etc

resource "digitalocean_volume" "notto-media-1" {
  name   = "notto-media-1"
  region = "lon1"
  size   = 10
  description             = "volume for storing django media file uploads"
}

resource "digitalocean_volume_attachment" "notto-media-1" {
  droplet_id = digitalocean_droplet.nottoboard-web.id
  volume_id = digitalocean_volume.notto-media-1.id
}

```
