### ISSUE TITLE
support for App platform maintenance option

### ISSUE THREAD

**Issue by maanenh** [digitalocean/terraform-provider-digitalocean#1359]
### Is your feature request related to a problem? Please describe.
The App Platform has a maintenance property in the App Spec (since march 2025).
It is not yet supported in this Provider.
Example from page: https://docs.digitalocean.com/products/app-platform/how-to/archive-restore
```
name: sample-golang
maintenance:
 archive: true
 offline_page_url: https://example.com/images/offline.png
services:
  ...
```

### Describe the solution you'd like
The maintenance option can be used
